curl -XPOST 'localhost:9200/elasticplaces/places/_search?pretty' -d '
{
	"size" : 3,
           "query":{
              "function_score":{
                 "query":{
                    "bool":{
                       "should":[
                          {
                             "match":{
                                "name":{
                                   "query":"alaxy",
                                   "boost":5
                                }
                             }
                          },
                          {
                             "match":{
                                "formatted_address":{
                                   "query":"alaxy",
                                   "boost":2
                                }
                             }
                          },
                          {
                             "match":{
                                "types":{
                                   "query":"alaxy",
                                   "boost":3 
                                }
                             }
                          }
                       ]
                    }
                 },
                 "functions":[
                    {
                       "field_value_factor":{
                          "field":"rating",
                          "factor":1.2,
                          "modifier":"sqrt",
                          "missing":2
                       }
                    }
                 ],
                 "boost_mode": "avg"
              }
           }
        }
'
